#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${CASH_MANAGER_POSTGRES_USER} WITH PASSWORD '${CASH_MANAGER_POSTGRES_PASSWORD}';
    CREATE DATABASE ${CASH_MANAGER_POSTGRES_DB} OWNER ${CASH_MANAGER_POSTGRES_USER};

EOSQL
