# Generated by Django 5.2.5 on 2025-09-17 09:52
import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_schemas(apps, schema_editor):
    # PostgresSQL:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE SCHEMA IF NOT EXISTS cash_manager;")


def delete_schemas(apps, schema_editor):
    # PostgresSQL:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP SCHEMA IF EXISTS cash_manager CASCADE;")


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(create_schemas, delete_schemas),
        migrations.CreateModel(
            name='CashFlowCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Наименование категории (ru)', max_length=256, unique=True)),
                ('alias', models.CharField(help_text='Наименование категории (en)', max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Категория ДДС',
                'verbose_name_plural': 'Категории ДДС',
                'db_table': 'cash_manager"."cash_flow_category',
            },
        ),
        migrations.CreateModel(
            name='CashFlowStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Наименование статуса (ru)', max_length=256, unique=True)),
                ('alias', models.CharField(help_text='Наименование статуса (en)', max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Статус ДДС',
                'verbose_name_plural': 'Статусы ДДС',
                'db_table': 'cash_manager"."cash_flow_status',
            },
        ),
        migrations.CreateModel(
            name='CashFlowSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Наименование подкатегории (ru)', max_length=256, unique=True)),
                ('alias', models.CharField(help_text='Наименование подкатегории (en)', max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Подкатегория ДДС',
                'verbose_name_plural': 'Подкатегории ДДС',
                'db_table': 'cash_manager"."cash_flow_subcategory',
            },
        ),
        migrations.CreateModel(
            name='CashFlowType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Наименование типа (ru)', max_length=256, unique=True)),
                ('alias', models.CharField(help_text='Наименование типа (en)', max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Тип ДДС',
                'verbose_name_plural': 'Типы ДДС',
                'db_table': 'cash_manager"."cash_flow_type',
            },
        ),
        migrations.CreateModel(
            name='CashFlowCategoryBySubcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_by_subcategory', to='cash_manager.cashflowcategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_by_subcategory', to='cash_manager.cashflowsubcategory')),
            ],
            options={
                'verbose_name': 'Связка Категории и Подкатегории ДДС',
                'verbose_name_plural': 'Связки Категорий и Подкатегорий ДДС',
                'db_table': 'cash_manager"."cash_flow_category_by_subcategory',
            },
        ),
        migrations.CreateModel(
            name='CashFlowCategoryByType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_by_type', to='cash_manager.cashflowcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_by_type', to='cash_manager.cashflowtype')),
            ],
            options={
                'verbose_name': 'Связка Категории и Типа ДДС',
                'verbose_name_plural': 'Связки Категорий и Подкатегорий ДДС',
                'db_table': 'cash_manager"."cash_flow_category_by_type',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания сущности')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Кол-во денежных средств в рублях', max_digits=10)),
                ('comment', models.CharField(help_text='Комментарий', max_length=512, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow', to='cash_manager.cashflowstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow', to='cash_manager.cashflowtype')),
            ],
            options={
                'verbose_name': 'Движение денежного средства',
                'verbose_name_plural': 'Движения денежных средств',
                'db_table': 'cash_manager"."cash_flow',
            },
        ),
    ]
